blog/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :users, only: [:update] #se puede generar solo una ruta especificada en el parmetro only
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/bienvenida", to: "home#index"

  root to: "home#index"

  get "perfil", to: "users#edit"
  

  get "articles/user/:user_id", to: "articles#from_author"
=begin
  resource :articles do
    get "user/:user_id", to: "articles#from_author", on: :collection #:members
  end
=end
  get "articles", to: "articles#index" #todos los articulos
  get "articles/new", to: "articles#new", as: :new_articles #controlador/accion # vista de formulario create
  get "articles/:id", to: "articles#show" #mostrar un artículo
  get "articles/:id/edit", to: "articles#edit", as: :edit_articles#editar un artículo
  patch "articles/:id", to: "articles#update" , as: :article #actualizar un artículo
  delete "articles/:id", to: "articles#destroy" #eliminar un nuevo artículo
  post "articles", to: "articles#create" #crear un nuevo artículo
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
    belongs_to :user #ingresar donde va el campo adicional o la llave foranea(singular)
    has_many :has_categories, dependent: :delete_all #:destroy
    has_many :categories, through: :has_categories #through -> a través de 
    attr_accessor :category_elements

    validates :title, :status, presence: true #validacion

    before_destroy :before_delete
    after_destroy :after_delete

    def before_delete
        puts "Antes de eliminar"
    end

    def after_delete
        puts "Despues de eliminar"
    end

    def save_categories
        #category elementes -> string 1,2,3...
        #convertirlo en arreglo 
        #category_array = category_elements.split(','); 
        #iterar ese arreglo
        return  has_categories.destroy_all if category_elements.nil? || category_elements.empty? 

        has_categories.where.not(category_id: category_elements).destroy_all

        category_elements.each do |category_id|
            #Crear HasCategory <articcle_id:1, category_id:2>_

            #valida que el la categoria no exista ya en el articulo, para evitar crear duplicados
            HasCategory.find_or_create_by(article: self, category_id: category_id)
=begin
            unless HasCategory.where(article:self, category_id: category_id).any?
                HasCategory.create(article: self, category_id: category_id)
            end

            if HasCategory.where(article:self, category_id: category_id).any?
            else
                HasCategory.create(article: self, category_id: category_id)
            end
=end
        end
    end

    scope :publicados, -> { where(:status => 1)}
    scope :ultimos, -> { order("created_at DESC").limit(3)}
    # Ex:- scope :active, lambda {where(:active => true)}
end

blog/app/models/category.rb
class Category < ApplicationRecord
    has_many :has_categories
    has_many :articles, through: :has_categories
end

blog/app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :delete_all #:destroy#borrar en cascada
   #nombre del modelo al que hereda la llave foranea(plural)
  has_one_attached :avatar
  #admin => true / false
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :find_article, except: [:new, :create, :index, :from_author] #only:[:show,:edit,:update,:destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    
    
    #after_action 

    def index
        @last_articles = Article.publicados.ultimos
        @articles = Article.all.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new 
        @article = Article.new #envia un articulo nuevo al formlario de la vista
        @categories = Category.all
    end

    def create
        @article = current_user.articles.create(article_params) 
        #title: params[:article][:title], content: params[:article][:content]
        @article.save_categories
        
=begin
        @article = Article.create(title: params[:article][:title], 
                                  content: params[:article][:content],
                                  user: current_user)
        render json: @article
=end
        redirect_to @article
    end

    def edit
        puts "\n\n\n  #{@article.persisted?} \n\n\n"
        @categories = Category.all
    end

    def update
        @article.update(article_params) #title: params[:article][:title], content: params[:article][:content]
        @article.save_categories
        redirect_to @article
    end

    def destroy
        @article.destroy
        redirect_to root_path
    end

    def find_article
        @article = Article.find(params[:id])
        #puts "ESTOY EN FIND ARTICLE"
    end
   
    def from_author
        @user = User.find(params[:user_id])
    end 

    #parametros fuertes
    def article_params
        params.require(:article).permit(:title, :content, :status, category_elements: [])
        #cuando se recibe un array, se debe indicar de esta forma
    end
end

blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    current_user.update(user_params)

    redirect_back(fallback_location: root_path) #redirecciona a la página anterior
  end

  def user_params
    params.require(:user).permit(:avatar)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

blog/app/views/articles/_article.html.erb
    <div class="card padding margin-top" >
        <h3 class="text-uppercase"> 
            <%= article.title%>
        </h3>
        <p class="text-secondary"><%= article.created_at%></p>
        <% if user_signed_in? %>
            <%= link_to "Ver más", article %>
        <% end %>
    </div>

blog/app/views/articles/_form.html.erb
<!--https://guides.rubyonrails.org/form_helpers.html-->
<%= form_with model: @article, local: true do |form| %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :category_elements %>
        <%# form.text_field :category_elements %>
        <%# comentarios %>
        <div class="row">
            <% @categories.each do |category|%>
                <label class="col-6 col-sm-4">
                    <%= form.check_box :category_elements, {multiple: true, checked: @article.categories.include?(category)}, category.id, nil %> <%#Al pasar la config {multiple} tranforma el string en un arreglo%>
                    <%= category.title %>
                </label>
            <% end %>
        </div>
    </div>

    <div class="field"> 
        <%= form.label :status %>
        <%= form.number_field :status %>
    </div>


    <div class="field"> 
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<%end%>

blog/app/views/articles/edit.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

blog/app/views/articles/from_author.html.erb
<div class="large-container center-block">
    <h1>Artículos publicados por <%= @user.email %> </h1>

    <%= render @user.articles %>
</div>

blog/app/views/articles/index.html.erb
<div class="large-container center-block">
    <h1>Ultimos publicados</h1>
    <% @last_articles.each do |article| %>
        <div class="card padding margin-top" >
            <h3 class="text-uppercase"> 
                <%= article.title%>
            </h3>
            <p class="text-secondary"><%= article.created_at%></p>
            <% if user_signed_in? %>
                <%= link_to "Ver más", article %>
            <% end %>
        </div>
    <%end%>
    
    <h1>Mis artículos</h1>
    <p>Cantidad de articulos: <%= @articles.count%></p>
    <%= render @articles %>


    <div>
        <%= will_paginate @articles %>
    </div>
</div>

blog/app/views/articles/new.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

blog/app/views/articles/show.html.erb
<div class="large-container center-block">
    <h1><%=@article.title%></h1>
    <div>
        <p>Escrito por: <strong> <%= @article.user.email %> </strong></p>
        <% if user_signed_in? && current_user.avatar.attached? %>
            <%= image_tag url_for(current_user.avatar), height: 30%>
        <% end %>
    </div>

    <div class="margin-top">
        <p class="label">Tags</p>
        <% @article.categories.each do |category| %>
            <span class="badge badge-pill padding" style="background-color: <%= category.color%>">
                <%= link_to category.title, category, class: "text-white"%>
            </span>
            
        <% end %>
    </div>

    <div>
        <%= @article.content %>
    </div>

    <div>
        <%= link_to "Eliminar articulo", @article, method: :delete %>
    </div>
    <div>
        <%= link_to 'Edit', edit_articles_path%>
    </div>
</div>

blog/app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-primary"%>
  </div>
<% end %>

blog/app/views/categories/edit.html.erb
<div class="small-container center-block">
    <% if current_user.admin? %>
        <h1>Editing Category</h1>

        <%= render 'form', category: @category %>

        <%= link_to 'Show', @category %> |
        <%= link_to 'Back', categories_path %>
    <% else %>
        <h1>Usted no tiene permisos para acceder a este recurso</h1>
    <% end %>
</div>

blog/app/views/categories/index.html.erb
<div class="small-container center-block">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Color</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
          <td><%= category.color %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path %>
</div>

blog/app/views/categories/new.html.erb
<div class="small-container center-block">
    <% if current_user.admin? %>
        <h1>New Category</h1>

        <%= render 'form', category: @category %>

        <%= link_to 'Back', categories_path %>
    <% else %>
        <h1>Usted no tiene permisos para acceder a este recurso</h1>
    <% end %>
</div>

blog/app/views/categories/show.html.erb
<div class="large-container center-block">
    <h1>Artículos publicados por <%= @category.title %> </h1>

    <%= render @category.articles %>
</div>

blog/app/views/home/index.html.erb
<h1>Hola <%= current_user.email %></h1>

<%= link_to "Inicio", root_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--devise-->
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

blog/app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
        <%= link_to "Artículos", articles_path, class:"nav-link"%>
    </li>

    <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Escribir", new_articles_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Mi perfil", perfil_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"nav-link"%>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Iniciar sesión", new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Registro", new_user_registration_path, class:"nav-link"%>
        </li>
        
    <% end %>
</nav>

blog/app/views/users/edit.html.erb
<div class="small-container center-block">
    <p class="font-weight-bold text-uppercase margin-top">Editar usuario</p>
    <% if user_signed_in? && current_user.avatar.attached? %>
        <%= image_tag url_for(current_user.avatar), height: 200%>
    <% end %>
    <%= form_with(model: current_user, local: true) do |form| %>
        <div class="field">
            <%= form.label :avatar %>
            <%= form.file_field :avatar %>
        </div>
    
        <div class="field">
            <%= form.submit "Guardar", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>